[package]
description = "Parser for the NTP protocol"
license = "LGPL-2.1+"
keywords = ["NTP","time","protocol","parser","nom"]
homepage = "https://github.com/rusticata/ntp-parser"
repository = "https://github.com/rusticata/ntp-parser.git"
name = "ntp-parser"
version = "0.1.1"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]

[dependencies]
nom = "1.2.4"
